=== joaogcrmorais/genAI-LBS-G5/lbs-files/processed/schemas/space.schema.json
{
    "$schema":  "https://json-schema.org/draft/2020-12/schema",
    "title":  "Space",
    "type":  "object",
    "required":  [
                     "source_used"
                 ],
    "properties":  {
                       "room_code":  {
                                         "type":  "string"
                                     },
                       "room_name":  {
                                         "type":  "string"
                                     },
                       "capacity":  {
                                        "type":  "string"
                                    },
                       "category":  {
                                        "type":  "string"
                                    },
                       "type":  {
                                    "type":  "string"
                                },
                       "owner":  {
                                     "type":  "string"
                                 },
                       "source_used":  {
                                           "type":  "string"
                                       },
                       "source_priority":  {
                                               "type":  [
                                                            "integer",
                                                            "number"
                                                        ]
                                           }
                   }
}

=== joaogcrmorais/genAI-LBS-G5/lbs-files/processed/space/spaces.json
[
    {
        "room_code":  "WLT",
        "room_name":  "Wolfson Lecture Theatre",
        "capacity":  "82",
        "category":  "LECT",
        "type":  "Tiered",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "Quad_Upper",
        "room_name":  "Upper Quad Area",
        "capacity":  "100",
        "category":  "FCTN",
        "type":  "Function",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.L1.101",
        "room_name":  "Upper Link Bridge",
        "capacity":  "60",
        "category":  "Standing",
        "type":  "Function",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "Transmed_LT",
        "room_name":  "Transmed Lecture Theatre",
        "capacity":  "59",
        "category":  "LECT",
        "type":  "Tiered",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "Sussex_Room",
        "room_name":  "Sussex Room",
        "capacity":  "14",
        "category":  "Boardroom",
        "type":  "Function",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.12",
        "room_name":  "SO.W3.12 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.10",
        "room_name":  "SO.W3.10 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.09",
        "room_name":  "SO.W3.09 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.08",
        "room_name":  "SO.W3.08 Seminar Room",
        "capacity":  "6",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.07",
        "room_name":  "SO.W3.07 Seminar Room",
        "capacity":  "6",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.06",
        "room_name":  "SO.W3.06 Seminar Room",
        "capacity":  "6",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.05",
        "room_name":  "SO.W3.05 Seminar Room",
        "capacity":  "6",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.04",
        "room_name":  "SO.W3.04 Neill Family Room",
        "capacity":  "6",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.03",
        "room_name":  "SO.W3.03 Carlsson Family Foundation Director\u0027s Room",
        "capacity":  "16",
        "category":  "Boardroom",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.02",
        "room_name":  "SO.W3.02 The Sir John Ritblat Boardroom",
        "capacity":  "30",
        "category":  "Boardroom",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W3.01",
        "room_name":  "SO.W3.01 Heritage Meeting Room",
        "capacity":  "6",
        "category":  "MEET",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W2.11",
        "room_name":  "SO.W2.11 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W2.10",
        "room_name":  "SO.W2.10 Seminar Room",
        "capacity":  "12",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W2.09",
        "room_name":  "SO.W2.09 Seminar Room",
        "capacity":  "12",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W2.08",
        "room_name":  "SO.W2.08 Seminar Room",
        "capacity":  "12",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W2.07",
        "room_name":  "SO.W2.07 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W2.04",
        "room_name":  "SO.W2.04 Alumni Meeting Room",
        "capacity":  "10",
        "category":  "MEET",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W2.02",
        "room_name":  "SO.W2.02 Finance Suite",
        "capacity":  "6",
        "category":  "Bloomberg",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W2.01",
        "room_name":  "SO.W2.01 Finance Suite",
        "capacity":  "10",
        "category":  "Bloomberg",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W1.08",
        "room_name":  "SO.W1.08 Faculty Room",
        "capacity":  "6",
        "category":  "Faculty",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W1.05",
        "room_name":  "SO.W1.05 Seminar Room",
        "capacity":  "10",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.W0.03",
        "room_name":  "SO.W0.03 Library Meeting Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E4.01",
        "room_name":  "SO.E4.01 Executive \"Terrace\" Meeting Room",
        "capacity":  "22",
        "category":  "Boardroom",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E3.14",
        "room_name":  "SO.E3.14 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E3.13",
        "room_name":  "SO.E3.13 Khalid Abdulatif Alhamad Room",
        "capacity":  "6",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E3.12",
        "room_name":  "SO.E3.12 Seminar Room",
        "capacity":  "10",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E3.11",
        "room_name":  "SO.E3.11 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E3.10",
        "room_name":  "SO.E3.10 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E3.09",
        "room_name":  "SO.E3.09 Seminar Room",
        "capacity":  "6",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E3.08",
        "room_name":  "SO.E3.08 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
        "room_code":  "SO.E3.07",
        "room_name":  "SO.E3.07 Seminar Room",
        "capacity":  "8",
        "category":  "SEMINAR",
        "type":  "Flat",
        "owner":  "SPMT",
        "source_used":  "Space Matrix",
        "source_priority":  1
    },
    {
